replicaCount: 1

image:
  repository: ghcr.io/open-telemetry/demo
  tag: "2.1.3-currency"
  pullPolicy: IfNotPresent

serviceAccount:
  name: opentelemetry-demo

env:
  OTEL_COLLECTOR_NAME: "otel-collector"
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "cumulative"
  CURRENCY_PORT: "8080"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://$(OTEL_COLLECTOR_NAME):4317"
  VERSION: "2.1.3"
  OTEL_RESOURCE_ATTRIBUTES: "service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=2.1.3"
