apiVersion: v2
name: llm-service
description: OpenTelemetry Demo - LLM Service (Python)
version: 0.0.1
dependencies:
  - name: basic-app
    version: 0.1.7
    repository: https://registry.devopsnow.io/chartrepo/public
