apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app.kubernetes.io/name: {{ include "postgresql-service.name" . }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      name: tcp-service
      targetPort: service
  selector:
    app.kubernetes.io/component: postgresql
