apiVersion: v2
name: shipping-service
description: OpenTelemetry Demo - Shipping Service (Rust)
version: 0.0.1
dependencies:
  - name: basic-app
    version: 0.1.7
    repository: https://registry.devopsnow.io/chartrepo/public
