apiVersion: v1
kind: Service
metadata:
  name: accounting
  labels:
    app.kubernetes.io/name: {{ include "accounting-service.name" . }}
    app.kubernetes.io/component: accounting
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: tcp-service
      targetPort: service
  selector:
    app.kubernetes.io/component: accounting

