apiVersion: v2
name: payment-service
description: OpenTelemetry Demo - Payment Service (JavaScript)
version: 0.0.1
dependencies:
  - name: basic-app
    version: 0.1.7
    repository: https://registry.devopsnow.io/chartrepo/public
