apiVersion: v2
name: product-reviews-service
description: OpenTelemetry Demo - Product Reviews Service (Python)
version: 0.0.1
dependencies:
  - name: basic-app
    version: 0.1.7
    repository: https://registry.devopsnow.io/chartrepo/public
