basic-app:
  configMap: {}
  image:
    repository: ghcr.io/open-telemetry/demo
    tag: 2.1.3-product-reviews
  imagePullSecrets: []
  ingress:
    enabled: false
  podAnnotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
    prometheus.io/scrape: 'true'
  resource:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 8080
