replicaCount: 1

image:
  repository: ghcr.io/open-telemetry/demo
  tag: "2.1.3-recommendation"
  pullPolicy: IfNotPresent

serviceAccount:
  name: opentelemetry-demo

env:
  OTEL_COLLECTOR_NAME: "otel-collector.devopsnow.svc.cluster.local"
  OTEL_LOGS_EXPORTER: "none"
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "cumulative"
  RECOMMENDATION_PORT: "8080"
  PRODUCT_CATALOG_ADDR: "product-catalog:8080"
  OTEL_PYTHON_LOG_CORRELATION: "true"
  PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: "python"
  FLAGD_HOST: "flagd"
  FLAGD_PORT: "8013"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://$(OTEL_COLLECTOR_NAME):4317"
  OTEL_RESOURCE_ATTRIBUTES: "service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=2.1.3"
