apiVersion: v1
kind: Service
metadata:
  name: ad
  labels:
    app.kubernetes.io/name: {{ include "ad-service.name" . }}
    app.kubernetes.io/component: ad
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: tcp-service
      targetPort: service
  selector:
    app.kubernetes.io/component: ad
