apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fraud-detection-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "fraud-detection-service.name" . }}
    app.kubernetes.io/component: fraud-detection
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: fraud-detection
  template:
    metadata:
      labels:
        app.kubernetes.io/component: fraud-detection
        app.kubernetes.io/name: {{ include "fraud-detection-service.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: fraud-detection
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # Dynamic Service name from metadata.label
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['app.kubernetes.io/component']
            # Direct env from values.yaml (loop)
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}

