apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend-proxy-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "frontend-proxy-service.name" . }}
    app.kubernetes.io/component: frontend-proxy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend-proxy
        app.kubernetes.io/name: {{ include "frontend-proxy-service.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: frontend-proxy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: service
          env:
            # Dynamic Service name from metadata.label
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['app.kubernetes.io/component']
            # Direct env from values.yaml (loop)
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            - name: envoy-config
              mountPath: /home/envoy/envoy.yaml
              subPath: envoy.yaml
              readOnly: true
      volumes:
        - name: envoy-config
          configMap:
            name: {{ include "frontend-proxy-service.fullname" . }}-envoy-config

