apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-proxy
  labels:
    app.kubernetes.io/name: {{ include "frontend-proxy-service.name" . }}
    app.kubernetes.io/component: frontend-proxy
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: demo-store.stackgen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-proxy
                port:
                  number: 8080
