apiVersion: v2
name: flagd-ui-service
description: OpenTelemetry Demo - Flagd UI Service (Elixir)
version: 0.0.1
dependencies:
  - name: basic-app
    version: 0.1.7
    repository: https://registry.devopsnow.io/chartrepo/public
