basic-app:
  image:
    repository: ghcr.io/open-telemetry/demo
    tag: flagd-ui
  imagePullSecrets: []
  ingress:
    enabled: false
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
  resource:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 8080
