apiVersion: v1
kind: Service
metadata:
  name: flagd-ui
  labels:
    app.kubernetes.io/name: {{ include "flagd-ui-service.name" . }}
    app.kubernetes.io/component: flagd-ui
spec:
  type: ClusterIP
  ports:
    - port: 4000
      name: tcp-service
      targetPort: service
  selector:
    app.kubernetes.io/component: flagd-ui
