apiVersion: v2
name: flagd-service
description: OpenTelemetry Demo - Flagd Service (Go)
version: 0.0.1
dependencies:
  - name: basic-app
    version: 0.1.7
    repository: https://registry.devopsnow.io/chartrepo/public
