apiVersion: v2
name: ad-service
description: OpenTelemetry Demo - Ad Service (Java)
version: 0.0.1
dependencies:
  - name: basic-app
    version: 0.1.7
    repository: https://registry.devopsnow.io/chartrepo/public
